### ISSUE TITLE
Getting Blank Screen From SDK

### ISSUE THREAD

**Issue by Paras3112** [postpayio/react-native-postpay-widget-example#1]
We are using your payment gateway but in this we have used your demo but we are facing issue of blank scree. 

Please let us know what is the problem with SDK. 

We have pass required details from our end. 

Please take a look of below video for the same. 

Video - https://drive.google.com/file/d/1xTpXoo49OdGtlvxPCdwoa3xT8pYf_Hwr/view?usp=sharing

Please guide us on this thing. 

Thanks in advance.

**Comment by minhchienwikipedia** [comment]
Hi @Paras3112 we had made some changes in Example, you can pull the latest code and test it again. I'll close this issue, you can open it whenever you want
